version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - ./gradlew dependencies  # or your build tool command
  build:
    commands:
      - echo "Building the application..."
      - ./gradlew build         # or your build command
  post_build:
    commands:
      - echo "Packaging the artifact..."
      - cp build/libs/your-app.jar your-app.jar
artifacts:
  files:
    - your-app.jar
